"""recheck

Revision ID: 156a9925f575
Revises: 3c0237a0b824
Create Date: 2021-07-03 22:30:01.746590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156a9925f575'
down_revision = '3c0237a0b824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('categorical_positions',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('preliminary_positions',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('preliminary_positions',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('categorical_positions',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
