"""empty message

Revision ID: 267207106283
Revises: d9e3f40b32ff
Create Date: 2021-04-25 20:38:47.701250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267207106283'
down_revision = 'd9e3f40b32ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
