"""empty message

Revision ID: 2824eb216822
Revises: e1c18da567f9
Create Date: 2021-04-03 11:13:12.064405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2824eb216822'
down_revision = 'e1c18da567f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('program', sa.Integer(), nullable=True))
    op.add_column('link', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'program', ['program'], ['id'])
    op.create_foreign_key(None, 'link', 'user', ['user'], ['id'])
    op.drop_column('link', 'user_id')
    op.drop_column('link', 'program_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('program_id', sa.INTEGER(), nullable=True))
    op.add_column('link', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'link', 'program', ['program_id'], ['id'])
    op.drop_column('link', 'user')
    op.drop_column('link', 'program')
    # ### end Alembic commands ###
