"""empty message

Revision ID: 2f1d39eae910
Revises: 267207106283
Create Date: 2021-04-29 19:30:14.119615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1d39eae910'
down_revision = '267207106283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accreditation_id', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('status')
        batch_op.drop_column('city')
        batch_op.drop_column('accreditation_id')

    # ### end Alembic commands ###
