"""tests

Revision ID: 371ec55cca8e
Revises: cd67944d3001
Create Date: 2021-04-16 00:12:41.135776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371ec55cca8e'
down_revision = 'cd67944d3001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testname', sa.String(length=140), nullable=True),
    sa.Column('score', sa.String(length=140), nullable=True),
    sa.Column('accuracy', sa.String(length=140), nullable=True),
    sa.Column('reaction_time', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timestamp'), 'test', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_timestamp'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
