"""name_and_shame

Revision ID: 58ee79cb1133
Revises: 40fa293b9fe7
Create Date: 2021-07-02 19:33:01.520404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ee79cb1133'
down_revision = '40fa293b9fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview__impression', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_and_shame', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview__impression', schema=None) as batch_op:
        batch_op.drop_column('name_and_shame')

    # ### end Alembic commands ###
