"""add specialty to programs

Revision ID: 6e515ae61804
Revises: 5c697cc0240d
Create Date: 2021-04-05 09:46:37.102681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e515ae61804'
down_revision = '5c697cc0240d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('specialty', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'specialty')
    # ### end Alembic commands ###
