"""add interview_date model

Revision ID: 76328bee6d0a
Revises: bf799e39ca80
Create Date: 2021-04-05 10:28:03.398765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76328bee6d0a'
down_revision = 'bf799e39ca80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview__date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('full', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview__date_date'), 'interview__date', ['date'], unique=False)
    op.create_index(op.f('ix_interview__date_full'), 'interview__date', ['full'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview__date_full'), table_name='interview__date')
    op.drop_index(op.f('ix_interview__date_date'), table_name='interview__date')
    op.drop_table('interview__date')
    # ### end Alembic commands ###
