"""post interview communications

Revision ID: 7c6a29e1360d
Revises: 58ee79cb1133
Create Date: 2021-07-03 18:13:12.144198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6a29e1360d'
down_revision = '58ee79cb1133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_interview_communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date_of_communication', sa.DateTime(), nullable=True),
    sa.Column('type_of_communication', sa.String(length=500), nullable=True),
    sa.Column('personalized', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tally', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_interview_communication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_interview_communication_date_of_communication'), ['date_of_communication'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_interview_communication_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_interview_communication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_interview_communication_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_interview_communication_date_of_communication'))

    op.drop_table('post_interview_communication')
    # ### end Alembic commands ###
