"""empty message

Revision ID: 995523e170ef
Revises: 61f6ef00810d
Create Date: 2021-04-02 17:49:37.995959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995523e170ef'
down_revision = '61f6ef00810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_timestamp'), 'program', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_timestamp'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
