"""state

Revision ID: a58b93e77732
Revises: c9e0bb82b37b
Create Date: 2021-04-05 14:16:39.878167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58b93e77732'
down_revision = 'c9e0bb82b37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('state', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'state')
    # ### end Alembic commands ###
