"""programs have posts

Revision ID: a97dd9713114
Revises: feafb92ebbdf
Create Date: 2021-04-03 16:59:31.167682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97dd9713114'
down_revision = 'feafb92ebbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('program_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'program', ['program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'program_id')
    # ### end Alembic commands ###
