"""add unavailable_dates

Revision ID: bf799e39ca80
Revises: 6e515ae61804
Create Date: 2021-04-05 10:15:57.978631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf799e39ca80'
down_revision = '6e515ae61804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('unavailable_dates', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_interview_unavailable_dates'), 'interview', ['unavailable_dates'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_unavailable_dates'), table_name='interview')
    op.drop_column('interview', 'unavailable_dates')
    # ### end Alembic commands ###
